# 动手练习：批量法向量计算

## 1️⃣ 目标

给 N 个三角形的顶点 `v0, v1, v2`，计算每个三角形的单位法向量。



In [4]:
import numpy as np
npoints = 1000
v0 = np.random.rand(npoints,3)
v1 = np.random.rand(npoints,3)
v2 = np.random.rand(npoints,3)
print(v0)
print(v1)
print(v2)


[[0.28144027 0.18494432 0.34650636]
 [0.178698   0.7686746  0.42145482]
 [0.08173635 0.76071113 0.95148746]
 ...
 [0.02232242 0.75676797 0.76703475]
 [0.59273599 0.86953867 0.87772524]
 [0.12998795 0.97953984 0.01818076]]
[[0.9183029  0.23786933 0.41568471]
 [0.88271595 0.43039523 0.89823087]
 [0.22996319 0.41424239 0.88677942]
 ...
 [0.85511834 0.89995525 0.58079452]
 [0.72076205 0.31323371 0.81475017]
 [0.82004143 0.0914146  0.07684931]]
[[0.18241492 0.64063354 0.5072724 ]
 [0.89650015 0.20186208 0.3333423 ]
 [0.33046227 0.44973434 0.84457751]
 ...
 [0.01814161 0.0323012  0.11698527]
 [0.27177372 0.55048137 0.98410808]
 [0.54526255 0.18616357 0.4622275 ]]


In [3]:
v01 = v1-v0
v02 = v2-v0
face_normal = np.cross(v01,v02)
print(face_normal)

[[-0.03386958  0.5822595   0.0971127 ]
 [ 0.01709496  0.31984562  0.26717123]
 [ 0.02739641 -0.12039948  0.1071939 ]
 ...
 [ 0.10183003  0.09155163 -0.11818917]
 [ 0.05241475 -0.04854005  0.04959326]
 [ 0.220611    0.18295075  0.08855291]]


In [ ]:
normal = face_normal / np.linalg.norm(face_normal, axis=1,keepdims=True)
print(normal)

ValueError: operands could not be broadcast together with shapes (1000,3) (1000,) 