第一课： numpy 的基本用法入门

In [1]:
import numpy as np


points = np.array([
    [0,0,0],
    [1,0,0],
    [0,1,0],
    [0,0,1]
])

print(points)
print(points.shape)

print(points[:,2])
print(points[0:2,1])

[[0 0 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]]
(4, 3)
[0 0 0 1]
[0 0]


In [2]:
random_points = np.random.randn(1000,3)
print(random_points)

[[-0.40701924  0.71446613  1.45134136]
 [-0.03749332 -1.41003916  1.78977202]
 [-0.0637586   0.67859607 -0.96757726]
 ...
 [ 0.37958906  0.62269167 -0.16784722]
 [ 1.90381149  0.75899656  0.89996978]
 [ 1.86122626  0.76332553  0.80634254]]


In [3]:
trans_points = random_points + np.array([1,2,3])
print(trans_points)

[[0.59298076 2.71446613 4.45134136]
 [0.96250668 0.58996084 4.78977202]
 [0.9362414  2.67859607 2.03242274]
 ...
 [1.37958906 2.62269167 2.83215278]
 [2.90381149 2.75899656 3.89996978]
 [2.86122626 2.76332553 3.80634254]]


In [8]:
theta = np.pi/2
R = np.array(
    [
        [np.cos(theta), -np.sin(theta),0],
        [np.sin(theta), np.cos(theta),0],
        [0,0,1]
    ]
)
print(R)
print(R.shape)

[[ 6.123234e-17 -1.000000e+00  0.000000e+00]
 [ 1.000000e+00  6.123234e-17  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  1.000000e+00]]
(3, 3)


In [7]:
t = np.array([1,2,3])
print(t)
print(t.shape)

[1 2 3]
(3,)


In [9]:
transform_points = trans_points @ R.T + t
print(transform_points)

[[-1.71446613  2.59298076  7.45134136]
 [ 0.41003916  2.96250668  7.78977202]
 [-1.67859607  2.9362414   5.03242274]
 ...
 [-1.62269167  3.37958906  5.83215278]
 [-1.75899656  4.90381149  6.89996978]
 [-1.76332553  4.86122626  6.80634254]]


numpy的基本函数：
1. np.array()
2. np.zeros()
3. np.ones()
4. np.arange()
5. np.linspace()
6. np.random.rand()
7. np.random.randint()
8. np.random.randn()
9. np.random.seed()
10. np.random.shuffle()
11. np.random.permutation()
12. np.random.choice()

In [10]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
dot_product = np.dot(v1,v2)
print(dot_product)

32


In [11]:
cross_product = np.cross(v1, v2)
print(cross_product)


[-3  6 -3]


In [13]:
norm_v1 = np.linalg.norm(v1)
norm_v2 = np.linalg.norm(v2)
print(norm_v1, norm_v2)
norm_l1_v1 = np.linalg.norm(v1, ord = 1)
norm_l2_v1 = np.linalg.norm(v1, ord = 2)
print(norm_l1_v1,norm_l2_v1)

3.7416573867739413 8.774964387392123
6.0 3.7416573867739413


In [17]:
cos_theta = np.dot(v1,v2) / (np.linalg.norm(v1)*np.linalg.norm(v2))
print(cos_theta)
theta_rad = np.arccos(cos_theta)
print(theta_rad)
theta_deg = np.degrees(theta_rad)

0.9746318461970762
0.2257261285527342
